services:
  database:
    image: postgres:16.2-alpine
    container_name: nestjs-drizzle-multiple-schemas
    healthcheck:
      retries: 12
      interval: 1s
      timeout: 1s
      test: [ "CMD-SHELL", "pg_isready -d <USER_NAME> -U <USER_NAME>" ]
    environment:
      POSTGRES_USER: <USER_NAME>
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
