services:
  database:
    image: postgres:16.2-alpine
    container_name: nestjs-drizzle-multiple-schemas
    healthcheck:
      retries: 12
      interval: 1s
      timeout: 1s
      test: [ "CMD-SHELL", "pg_isready -d drizzle-orm -U drizzle-orm" ]
    environment:
      POSTGRES_USER: drizzle-orm
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
